[package]
name = "_001-hello"
version = "0.1.0"
authors = ["Raspberry Pi <raspberrypisig@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
